### ISSUE TITLE
Part 2/3: Enable automatic OpenAPI model generation based on schema

### ISSUE THREAD

**Issue by andylamp** [andylamp/warestack-cli#2]
This issue tracks the progress of the following,

- Removing the dependency of the internal `warestack-api` due to its proprietary nature,
- Enable the ability to compile against the latest version of the API by automatically generating the models using [oapi-codegen](https://github.com/deepmap/oapi-codegen).

This functionality will be also baked in the release pipelines. Though, note that only one version of the API can be compiled against each version - ideally the latest available.

**Comment by dkargatzis** [comment]
I am wondering if we could support an auto-update mechanism in a later version. In detail:

**1. Fetching the Latest API Version**

- Have an endpoint in the API that gives information about the current API version.
- In the CLI, add functionality to call this endpoint to get the current API version.

**2. Version Comparison**

- The CLI should have its current version (associated with the API version it was last built against) embedded within it. We can use Go's build-time variables to set this.
- Compare the CLI's current API version with the latest version fetched from the API.

**3. Auto-Update Mechanism**

- If the versions are different, notify the user that an update is available.
- Download the latest version of the CLI (we could host binaries on GitHub releases or another hosting solution).
- Replace the current binary with the latest version.

**Comment by andylamp** [comment]
Hey,

Notifying of a new version is easy - actually upgrading the binary automatically is not as easy. Of note is that on Windows it is _very_ hard to do.  Let's scope this task once the basic one is completed.

**Comment by andylamp** [comment]
closing them as they have been completed
