### ISSUE TITLE
Part 3/3: Enable firebase login though the API

### ISSUE THREAD

**Issue by andylamp** [andylamp/warestack-cli#3]
As the title says, this involves using the refactor project to allow login using firebase. It will use the updated flow provided by the `warestack-core-api`.

**Comment by dkargatzis** [comment]
I will provide you with the CLI-UI authentication flow as discussed, by the end of the week.

**Comment by andylamp** [comment]
cool, appreciated.

**Comment by dkargatzis** [comment]
A new group is created in Warestack's Google Admin Workspace. Additionally, an account is created and activated in Warestack Console. You can use the credentials below for signing in here [warestack.com](https://www.warestack.com/)

Email Alias: tony.sentoni@warestack.com
Password: PipisGrande1

**Comment by andylamp** [comment]
closing them as they have been completed
